### ISSUE TITLE
jest and node v12 gets stuck while importing file using styled jsx with postcss plugin

### ISSUE THREAD

**Issue by ramasilveyra** [giuseppeg/styled-jsx-plugin-postcss#31]
Jest gets stuck while importing file using styled jsx with this plugin.

Repro https://github.com/ramasilveyra/bug-repro-next-styled-jsx-jest.

Not sure if this is the right place to report this bug. If is not I can open another issue in styled jsx or postcss or jest repo.

**Comment by joonhocho** [comment]
I think this is related to https://github.com/giuseppeg/styled-jsx-plugin-postcss/issues/32.
Upon investigation, I think the problem is due to infinite while loop that is caused by never resolved promise.
https://github.com/giuseppeg/styled-jsx-plugin-postcss/blob/master/index.js#L20

I think to fix this, we need to make everything sync.

This plugin uses `postcss-load-plugin` that uses `cosmiconfig`:

`cosmiconfig` has sync API available https://github.com/davidtheclark/cosmiconfig#synchronous-api.

So we need to fix https://github.com/michael-ciniawsky/postcss-load-plugins/blob/11f7173d8e84a048ba5d8a9afc8b3a3dfa19d362/index.js#L46 here to use sync version.

then https://github.com/giuseppeg/styled-jsx-plugin-postcss/blob/master/processor.js#L20 here can be sync too.

then we don't need the wait while loop anymore.

**Comment by ramasilveyra** [comment]
Yes, I arrived to a similar place while investigating.

Maybe `deasync` doesn't play well together with jest (jest mocks globals)? If is that we can try to replace it with execSync, eg: https://joecreager.com/5-reasons-to-avoid-deasync-for-node-js/ `5.  There are alternatives.` title.

**Comment by joonhocho** [comment]
It's not just Jest problem. This is not working without Jest as well.
I am using Next.js + styled-jsx + styled-jsx-plugin-postcss and it hangs for the reason I stated.
This plugin just is not working for me at all.

**Comment by JosephScript** [comment]
Would you like to submit a pull request to fix it?

**Comment by assimovt** [comment]
@joonhocho have you found the workaround for this issue? Bumped into the same problem.

**Comment by StarpTech** [comment]
I implemented sync support in [postcss-load-plugins](https://github.com/michael-ciniawsky/postcss-load-plugins/pull/119)

Feel free to provide a first draft pointing to that version.

**Comment by StarpTech** [comment]
I think this is not the full story. As soon as a postcss plugin is async we can't use the sync version. An error is thrown by postcss. `styled-jsx` has to support async plugins.

**Comment by giuseppeg** [comment]
@StarpTech thanks for looking into this and sorry for the troubles! Indeed the problem is that Babel (styled-jsx) is synchronous whereas PostCSS' API is async. When I made this repo (a proof of concept) I used deasync but it is a super hack. 

As pointed out by @ramasilveyra the solution here could be to rewrite the plugin to use Node.js' `execSync` to run a node script that compiles the styles with PostCSS. 

Unfortunately I don't have time to make those changes but if anybody feels like submitting a PR, I'd be happy to review, give feedback and merge it if the approach works.

**Comment by StarpTech** [comment]
This issue and https://github.com/zeit/next.js/issues/12727 changed my mind about how styling can be applied with regard to the best tradeoffs. I'm no longer interested in supporting Postcss in styled-jsx. I use built-in SCSS modules for now and fallback to styled-jsx when I need `dynamic` CSS. Thanks for your feedback.

**Comment by giuseppeg** [comment]
Please [consider sponsoring](https://github.com/sponsors/giuseppeg) this bug fix if it is urgent or important for you and your company. Anybody who is interested can [DM me on Twitter](https://twitter.com/giuseppegurgone) before doing the donation.

**Comment by MaheshZ** [comment]
post css does have a syncrhonous api. I just wrote below code and on windows atleast it ran fine, still need to ensure none of config reading part uses asynch. That would pretty much mean using `var cosmiconfigSync  = require('cosmiconfig')` instead of cosmiConfig in the postcss-load-plugins package.

```
const loopWhile = require('deasync').loopWhile
const processor = require('./processor')
const postcss = require('postcss')

const _processor = postcss()

module.exports = (css, settings) => {
  console.log("Css is", css)
  const cssWithPlaceholders = css
    .replace(/%%styled-jsx-placeholder-(\d+)%%/g, (_, id) =>
      `/*%%styled-jsx-placeholder-${id}%%*/`
    )
  let processedCss
  let wait = true

  function resolved(result) {
    console.log("processor resolved", result)
    processedCss = result.css
    wait = false
  }

  processedCss = _processor.process(cssWithPlaceholders, { from: false }).css
  // .then(console.log)
  //.then(resolved)

  // loopWhile(() => wait)
  console.log( "returning:", processedCss.replace(/\/\*%%styled-jsx-placeholder-(\d+)%%\*\//g, (_, id) =>
  `%%styled-jsx-placeholder-${id}%%`))
  
  return processedCss.replace(/\/\*%%styled-jsx-placeholder-(\d+)%%\*\//g, (_, id) =>
    `%%styled-jsx-placeholder-${id}%%`
  )
}

```

**Comment by giuseppeg** [comment]
@MaheshZ I think that the problem is that not all plugins are synchronous

**Comment by MaheshZ** [comment]
> @MaheshZ I think that the problem is that not all plugins are synchronous

You mean babel plugins or postcss plugins. From what I read babel expects plugins to be sync. Postcss supports async plugins. And the post css plugin itself has an asynchronous api.

**Comment by Ginhing** [comment]
Same problem from a Nextjs project intergrated Storybook which using `styled-jsx-plugin-postcss@2.0.1`. It hangs forever every time to run `start-storybook` but will get job done after disabled this plugin.
