### ISSUE TITLE
v3 performance issue: 2x to 5x more slower

### ISSUE THREAD

**Issue by ramasilveyra** [giuseppeg/styled-jsx-plugin-postcss#39]
Trying v3 in a big project makes build time 2x to 5x more slower. (tested by running build in different big apps with v2 and v3)

This must be related to that right now a new node child process is created per css compilation.

~Maybe a solution can be to create only one node child process, keep the child process alive with something like https://stackoverflow.com/a/50451612, communicate with the child via message and kill it when father process exits? Still thinking about this~, not sure if is going to work, happy to heard ideas.

**Comment by giuseppeg** [comment]
Not sure if that works but I wonder if moving this to another file and exporting `processor` might speed things up https://github.com/giuseppeg/styled-jsx-plugin-postcss/blob/ea4894945232d5c786a5b8a43ae811ebc911072c/processor.js#L1-L27 

Maybe you can try in a local branch with your project?

**Comment by ramasilveyra** [comment]
Found that for my specific case I don't need async plugin support.

Workaround if you only use sync plugins is to use a sync version of styled-jsx-plugin-postcss:
`.babelrc.js`:
```js
const path = require('path');

module.exports = {
  presets: [
    [
      'next/babel',
      {
        'styled-jsx': {
          plugins: [path.resolve(__dirname, './tools/build/styled-jsx-plugin-postcss.js')],
        },
      },
    ],
  ],
};
```
`tools/build/styled-jsx-plugin-postcss.js`:
```js
const postcss = require('postcss');
const postcssrc = require('postcss-load-config');

let plugins;
let processor;

module.exports = (css, settings = {}) => {
  const cssWithPlaceholders = css.replace(
    /%%styled-jsx-placeholder-(\d+)%%/g,
    (_, id) => `/*%%styled-jsx-placeholder-${id}%%*/`,
  );

  if (!plugins) {
    plugins = postcssrc.sync(settings.env || process.env, settings.path, { argv: false }).plugins;
  }

  if (!processor) {
    processor = postcss(plugins);
  }

  const result = processor.process(cssWithPlaceholders, { from: false }).css;

  return result.replace(
    /\/\*%%styled-jsx-placeholder-(\d+)%%\*\//g,
    (_, id) => `%%styled-jsx-placeholder-${id}%%`,
  );
};
```

If somebody else finds this useful, let me know, I can publish the package maybe as `styled-jsx-plugin-postcss-sync` 😅.

**Comment by giuseppeg** [comment]
@ramasilveyra cool! FWIW this package could support both via a plugin option and the implementation would be trivial.

**Comment by cullylarson** [comment]
I'm having a similar issue. My nextjs build went from taking less than a minute to about 20 minutes. I tracked the issue down to `styled-jsx-plugin-postcss`. If I use @ramasilveyra 's solution, it speeds back up. However, I hit a `Use process(css).then(cb) to work with async plugins` error at some point and the build fails. I assume this is because the sync version doesn't work with async plugins. I'm willing to spend some time fixing this issue. Though I've never done any postcss plugin development.

**Comment by cullylarson** [comment]
I made a small change to @ramasilveyra 's code and it ends up working with async plugins. The nextjs production build is back to finishing in under a minute. However, this doesn't seem to work for nextjs development mode. All of my jsx styles are empty.

**UPDATE**: Actually, I don't think the production build worked. I mean, it finishes. But I think it has the same issue of jsx styles being empty. The problem seems to be that each call to styled-jsx-plugin-postcss is done synchronously. So if you have a lot of style-jsx to process, it takes a long time. Is there a way to make a styled-jsx plugin run asynchronously?

Here's the code. I just made the exported function `async` and added an `await` to the `processor.process` call.

```js
const postcss = require('postcss');
const postcssrc = require('postcss-load-config');

let plugins;
let processor;

module.exports = async (css, settings = {}) => {
  const cssWithPlaceholders = css.replace(
    /%%styled-jsx-placeholder-(\d+)%%/g,
    (_, id) => `/*%%styled-jsx-placeholder-${id}%%*/`,
  );

  if (!plugins) {
    plugins = postcssrc.sync(settings.env || process.env, settings.path, { argv: false }).plugins;
  }

  if (!processor) {
    processor = postcss(plugins);
  }

  const resultFull = await processor.process(cssWithPlaceholders, { from: false });
  const result = resultFull.css;

  return result.replace(
    /\/\*%%styled-jsx-placeholder-(\d+)%%\*\//g,
    (_, id) => `%%styled-jsx-placeholder-${id}%%`,
  );
};
```

**Comment by cullylarson** [comment]
I did some instrumenting. The bottleneck is loading the postcss config every time styled-jsx-plugin-postcss is called (`loader(options.env || process.env, options.path)`). You have an attempt at optimization in `processor.js` (`if (!plugins)...`), but since you're running `processor.js` using `spawnSync`, `processor.js` will be reloaded every time you spawn. So the config has to be reloaded. This takes about a second on my machine. The rest of the code takes a few tens of milliseconds.

I figured out a way to only load the config once and share it between spawns. It cuts each run of styled-jsx-plugin-postcss down to tens of milliseconds (the first run is still a bit over a second, since it has to load the config). I'll post what I have tomorrow and maybe get a pull request together.

I tested with my nextjs project that was taking about 20 minutes to build. It's back down to under a minute. Development mode works as well.

**Comment by giuseppeg** [comment]
@cullylarson thanks for looking into this. I forgot to mention that I figured out a fix for a client during an audit. 

Anybody who wants to hire me to prepare a public patch can [reach out to me directly](https://giuseppegurgone.com/contact).

**Comment by cullylarson** [comment]
@giuseppeg Could you describe the general form of your solution? I mostly copied mine from https://github.com/wbyoung/babel-plugin-transform-postcss. The idea is to spawn a "server" script that loads the postcss config and then listens on a socket. Then when styled-jsx-plugin-postcss is called, it spawns a "client" script (needs to do this since the client is async) which sends CSS to the server over the socket. The server does the transform and sends the result back to the client.

Here's the code: https://gist.github.com/cullylarson/9913a31d145e2d263a009d2edd41762b

I'm not sure if I have time to create tests for this at the moment, so I don't know when I can get to a pull request. It would be a pretty big change to the plugin in any event. Would you be interested in merging these changes once I get around to a pull request?

**Comment by giuseppeg** [comment]
This was fixed in https://github.com/giuseppeg/styled-jsx-plugin-postcss/pull/49 [@swissredcross](https://github.com/swissredcross) sponsored this work ❤️
